### ISSUE TITLE
[2.0.0] iit and ddescribe not defined

### ISSUE THREAD

**Issue by ofairfoul** [mhevery/jasmine-node#362]
Personally I feel the main reason to use this over the existing jasmine node runner is for iit and ddescribe support. It now appears to be missing from 2.0 branch.

```
Failures:
  1) x encountered a declaration exception
    Message:
      ReferenceError: iit is not defined
```
